booksnob/config/urls.py
"""booksnob URL Configuration
"""
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^critic/', include('critic.urls')),
	url(r'^', include('reader.urls')),
	url(r'^djrestfraimw/', include('djrestfraimw.urls')),
	url(r'^docs/', include('rest_framework_swagger.urls')),
]

booksnob/critic/urls.py
from django.conf.urls import url
from critic import views

urlpatterns = [

	url(r'^thanks/', views.ThanksView.as_view()),
	url(r'^review/', views.ReviewView.as_view(), name='review_book'),
]

booksnob/critic/forms.py
from django import forms
from reader.actions import get_books

class ReviewForm(forms.Form):
	book_name = forms.ChoiceField(choices=[
		(book, book) for book in get_books()
	])
	text = forms.CharField(widget=forms.Textarea)

	def send_email(self):
		print('Book: {0}'.format(self.cleaned_data['book_name']))
		print('Message: {0}'.format(self.cleaned_data['text']))

booksnob/critic/views.py
from critic.forms import ReviewForm
from django.views.generic.edit import FormView
from django.views.generic import TemplateView

class ReviewView(FormView):
	template_name = 'critic/review.html'
	form_class = ReviewForm
	success_url = '/critic/thanks/'
		
	def form_valid(self, form):
		form.send_email()
		return super(ReviewView, self).form_valid(form)

class ThanksView(TemplateView):
	template_name = 'critic/thanks.html'

booksnob/critic/templates/critic/review.html
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
	<link rel="stylesheet" href="css.css" />
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
	<title></title>
	</head>
	<body>
		<form action="{% url 'review_book' %}" method="post" class="list-group-item">{% csrf_token %}
			<div  style="display:inline-block;">
				<label for="your_name" style="float:left; width:100px;">Book name:</label>
					<select id="id_book_name" name="book_name" style="width:200px;"> 
					{% for val, txt in form.fields.book_name.choices %}
						<option value="{{ val }}">{{ txt }}</option>
						}
					{% endfor %}
					</select>
			</div>
			<div>
				<label for="your_name" style="float:left; width:100px;">Text:</label>
				<textarea id="book_name" name="text" style="width:200px;">{{ form.form.text}} </textarea>
			</div>   
			<input type="submit" value="send"/>
		</form>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script
</html>

booksnob/critic/templates/critic/thanks.html
 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
	<head>
	<link rel="stylesheet" href="css.css" />
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
	<title></title>
	</head>
	<body>
		<h2 >Thanks</h2>
	</body>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script
</html>